name: "<Python package>"

on:
  push:
    branches: ["main", "dev"]
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches: ["main", "dev"]
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"] # Only 3.11 for now

    steps:
    - uses: actions/checkout@v4
    - name: "[âš™ï¸ğŸª¶ Install poetry]"
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: "[ğŸ Set up Python ${{ matrix.python-version }}]"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: "[ğŸª¶ Install dependencies]"
      run: |
        poetry env use python${{ matrix.python-version }}
        poetry install --with dev

    # - name: "[ğŸª¥Lint with flake8]"
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: "[ğŸ§ª Pytest]"
      run: |
        poetry run pytest
